### ISSUE TITLE
Unable to user "string" in as enum value

### ISSUE THREAD

**Issue by MQ-xz** [GrantBirki/json-yaml-validate#38]
Schema
```yml
args:
  - name:
      type: string
      required: true
    description:
      type: string
    required:
      type: boolean
    type:
      type: string
      enum: ["string", "url", "domain", "path", "status", "ip", "list"]
```

yml code

```yml
args:
  - description:
    name: domain
    required: false
    type: string
```

error got
```
| {
|     "file": "xxx/xxx.yml",
|     "errors": [
|       {
|         "path": "args.0.type",
|         "message": "args.0.type must be either function String() { [native code] }, url, domain, path, status, ip or list."
|       }
|     ]
|   },
```
