### ISSUE TITLE
Feature Request: Accept globs in `files` option

### ISSUE THREAD

**Issue by rhuanbarreto** [GrantBirki/json-yaml-validate#45]
I wanted to target all `deploy.yaml` files inside my `src` folder. It would be very useful to use:
```yaml
- name: deploy.yaml validation
  uses: GrantBirki/json-yaml-validate@v2.4.0
  with:
    yaml_as_json: "true"
    json_schema: ./infra/deploy.yaml.schema.json
    base_dir: ./src
    files: "src/**/deploy.yaml"
    comment: "true"
```
