### ISSUE TITLE
Github-provided .gitignore causes JSON files to be excluded

### ISSUE THREAD

**Issue by untulis** [GrantBirki/json-yaml-validate#55]
First off, thank you for this action!

I have a Github provided `.gitignore` that included the following:

```
# Thumbnails
._*
```

(TBH, I don't know what "thumbnails" are being referred to (maybe for an image gallery?))

This seems to have caused the default `Exclude` to basically think all files (at least JSON which I had, but I don't think it matters)

```
##[debug]using baseDir: src/data
##[debug]using glob: **/*.json
##[debug]found file: src/data/basic_team_info.json
##[debug]file matches exclude glob pattern: ._*
skipping due to exclude match: src/data/basic_team_info.json
```

Commenting out the "offending" `.gitignore` fixes the problem. 

Action configuration that triggered the issue:
```yaml
  json-yaml-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: json-yaml-validate
        id: json-yaml-validate
        uses: GrantBirki/json-yaml-validate@v2.6.1
        with:
          base_dir: src/data
          comment: true
```

Happy to create a sample repo (the one that found this is private) if that helps with reproduction. 

Thanks!

**Comment by GrantBirki** [comment]
@untulis Hey! 👋 Glad you are getting good use out of this Action.

I have great news for you, there is an input option in this Action to easily toggle off the usage of `.gitignore` files for exclusion.

- [`use_gitignore`](https://github.com/GrantBirki/json-yaml-validate/blob/53fae7e7ad5c90e1e232a227a23437ec31e6c75d/action.yml#L76-L79)

You can tweak your Action's configuration like so to remove the issue at hand:

```yaml
  json-yaml-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: json-yaml-validate
        id: json-yaml-validate
        uses: GrantBirki/json-yaml-validate@v2.6.1
        with:
          base_dir: src/data
          comment: true
          use_gitignore: "false" # <--- add this
```

After disabling your `.gitignore` file via the input option seen above, you can still have fine-grained control using [exclude files](https://github.com/GrantBirki/json-yaml-validate/tree/main?tab=readme-ov-file#excluding-files) that are custom to this Action.

The background of using the `.gitignore` file by default, was to make it a bit easier for users to ignore files from this Action that are also ignored by version control. That doesn't fit every use case though and that is why you can disable the option via the input option in cases like yours.

Hopefully that helps!
