### ISSUE TITLE
Feature: Support flat YAML

### ISSUE THREAD

**Issue by Bigyls** [GrantBirki/json-yaml-validate#69]
Hello,

I'm having a problem with a YAML file that I call flat:

```yaml
name: Test
author: Me
category: YAML
```

And when I try to create my schema I get the following error when launching the action:

```
name:
  type: string
  description: Name of the yaml value
  required: true
...
```

```
Error: workflow is not valid. 'schema.yml': yaml: unmarshal errors:
  line 3: cannot unmarshal !!map into string
```

Does anyone have an idea? I have the impression that this error is due to the handling of https://github.com/ketanSaxena/schema-validator

**Comment by GrantBirki** [comment]
👋 Hey @Bigyls! I tried to reproduce this error and I'm not able to see it. Here are some logs of a workflow run - [logs](https://github.com/GrantBirki/json-yaml-validate/actions/runs/10516437912/job/29138639313?pr=75#step:7:25) from this [pull request](https://github.com/GrantBirki/json-yaml-validate/pull/75).

**Comment by Bigyls** [comment]
Okay, I see! It was my local tests with act (https://github.com/nektos/act). 

Flat YAML works very well.


But now I get an error because my YAML file contains a “type” entry:

My YAML :
```
flags:
  - {
    type: "regex",
    content: "^test$",
    data: "case_insensitive",
  }
```

Schema : 
```
flags:
  - type: string
    type:
      type: string
      description: Type of the flag
      enum: ["regex", "static"]
    content:
      type: string
      description: Content of the flag
    data:
      type: string
      description: Data of the flag
```

Error : 
```
ERROR : YAMLException: duplicated mapping key at line 82, column -92:
        type:
        ^
```

There is a way to counter this problem or disable the check of "flags" in my yaml ?
