### ISSUE TITLE
Bug: Wrong file extension in summary and double check of same file

### ISSUE THREAD

**Issue by jprecuch** [GrantBirki/json-yaml-validate#70]
I'm using following configuration
```
      - name: Validate json ${{ inputs.json_configuration }} with schema
        uses: GrantBirki/json-yaml-validate@3a3d883daf915618a7503a2e9c04b8e57130a4b8 # v3.0.0
        with:
          use_gitignore: false
          files: |
            moonstone-configuration.json
            manifests-configuration.yaml
          json_schema: moonstone-schema.json
```
When the action passes it prints following summary
```
Run GrantBirki/json-yaml-validate@3a3d883daf915618a7503a2e9c04b8e57130a4b8
moonstone-configuration.json is valid
moonstone-configuration.json is valid
configuration.yaml is valid
✅ all 1 detected JSON files are valid
✅ all 2 detected YAML files are valid
```
There seems to be two issues:
1. It counted 3 files to be validated (why?), when I have only 2 in my "files". Based on info it checked same file twice?
2. It considers one of .json files to be YAML format for no reason or somewhere got additional yaml file to report
