### ISSUE TITLE
Field String Regex Validation

### ISSUE THREAD

**Issue by djrmarques** [GrantBirki/json-yaml-validate#8]
I think regex validation would be a very nice feature for this action. Not sure how easy it is to implement this. 

For example, the following schema file

```yaml
#schema.yaml
dev:
  - type: string
  - regex: arn:aws:s3:::[a-zA-Z0-9_\-]+\/\*
```
Should throw an error when validating this file

```yaml
#file.yaml
dev:
  - something-here # This would fail
```
